### ISSUE TITLE
Eu olhei sem querer

### ISSUE THREAD

**Issue by LeonardoFurtado** [allonsmandy/simple-page#1]
_EOM_

**Comment by allonsmandy** [comment]
poxa, por que você fez isso comigo? :'(

**Comment by LeonardoFurtado** [comment]
Mania de ver atualizações de quem eu sigo :c

**Comment by allonsmandy** [comment]
ah então ok :3

**Comment by LeonardoFurtado** [comment]
closing
![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)
